site_name: CalData's Modern Data Stack Training
theme:
  name: material
  logo: images/odi-square_logomark-blue.svg
  favicon: images/odi-circle_logomark-blue.png
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/quiz.js

repo_name: cagov/caldata-mdsa-training
repo_url: https://github.com/cagov/caldata-mdsa-training
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Overview: index.md
  - learning: learning-path.md
  - Code development:
      - Git: code/git.md
      - GitHub: code/github.md
      - Local repo setup: code/local-repo-setup.md
      - CI/CD concepts: code/ci-cd.md
      - CI/CD hands-on: code/ci-cd-hands-on.md
      - Azure DevOps: code/devops.md
  - Cloud data warehouses:
      - Snowflake: cloud-data-warehouses/snowflake.md
  - Data transformation:
      - dbt:
          - quiz: data-transformation/dbt/quiz-example.md
          - Part I Foundations and staging models: data-transformation/dbt/pt-i.md
          - Part II Documentation and testing: data-transformation/dbt/pt-ii.md
          - Part III Materializations and intermediate models: data-transformation/dbt/pt-iii.md
          - Part IV dbt docs and mart models: data-transformation/dbt/pt-iv.md
          - Part V Environments, jobs, CI/CD, and custom schemas: data-transformation/dbt/pt-v.md
      - TEST: data-transformation/TEST.md
      - dbt Core practice: data-transformation/dbt-core-practice.md
      - Practice answers: data-transformation/dbt-practice-answers.md
      - Advanced:
          - Macros & custom tests: data-transformation/advanced/macros-custom-tests.md
  - Integration and architecture:
      - End-to-end workflow: integration/end-to-end-workflow.md
      - Local to production: integration/local-to-production.md
      - Schema naming strategy: integration/schema-naming-strategy.md
  - Troubleshooting: self-assessment/troubleshooting.md
