site_name: CalData's Modern Data Stack Training
theme:
  name: material
  logo: /images/odi-square_logomark-blue.svg
  favicon: /images/odi-circle_logomark-blue.png
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

repo_name: cagov/caldata-mdsa-training
repo_url: https://github.com/cagov/caldata-mdsa-training
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      auto_title: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - git:
      - Overview of git: git/git.md
      - GitHub: git/github.md
      - Azure DevOps: git/devops.md
  - Cloud data warehouses:
      - Snowflake: cloud-data-warehouses/snowflake.md
  - dbt:
      - dbt Cloud: dbt/cloud.md
      - dbt Core: dbt/core.md
