name: terraform-validation

on:
  pull_request:
  push:
    branches: [main]

jobs:
  terraform-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: v1.9.0

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform fmt
        run: terraform -chdir=infra-template/terraform fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=infra-template/terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform -chdir=infra-template/terraform validate

      - name: tflint
        run: tflint --chdir=infra-template/terraform --recursive
